// import image from

export const products = [
  {
    id: 1,
    img: '/assets/sale-1.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ducimus pariatur, natus soluta dolore maxime impedit rem quaerat! Ipsam, numquam. Minima voluptate natus animi officia dicta eligendi accusantium voluptatibus commodi',
    blurhash: 'L6BDyi?F009a00H??wtSlVp0m+w^',
  },
  {
    id: 2,
    img: '/assets/sale-2.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ducimus pariatur, natus soluta dolore maxime impedit rem quaerat! Ipsam, numquam. Minima voluptate natus animi officia dicta eligendi accusantium voluptatibus commodi ',
    blurhash: 'LZKw?}?a.7V@~pIUV[WVxutQRQay',
  },
  {
    id: 3,
    img: '/assets/sale-3.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ducimus pariatur, natus soluta dolore maxime impedit rem quaerat! Ipsam, numquam. Minima voluptate natus animi officia dicta eligendi accusantium voluptatibus commodi',
    blurhash: 'L8GSGoIUIB00Ot00WY~V9FX8-p?a',
  },
  {
    id: 4,
    img: '/assets/sale-4.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ducimus pariatur, natus soluta dolore maxime impedit rem quaerat! Ipsam, numquam. Minima voluptate natus animi officia dicta eligendi accusantium voluptatibus commodi',
    blurhash: 'LBMtp*R5Fy.9~pxuWBW=Inoet7t8',
  },
  {
    id: 5,
    img: '/assets/sale-9.jpg',
    title: 'Solar Installation',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ducimus pariatur, natus soluta dolore maxime impedit rem quaerat! Ipsam, numquam. Minima voluptate natus animi officia dicta eligendi accusantium voluptatibus commodi',
    blurhash: 'L6O|U,00XSoz00aLIT?v_NkERORP',
  },
  {
    id: 6,
    img: '/assets/sale-6.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ducimus pariatur, natus soluta dolore maxime impedit rem quaerat! Ipsam, numquam. Minima lorem jsbnuibhjs n subjsoibgj sjgbnsdgui sjgbnsuih jhbisubh sjjskbhsug joij',
    blurhash: 'LFBNTi9EJCIUu6xuD$xvM_tSVWjE',
  },
  {
    id: 7,
    img: '/assets/sale-7.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ducimus pariatur, natus soluta dolore maxime impedit rem quaerat! Ipsam, numquam. Minima lorem jsbnuibhjs n subjsoibgj sjgbnsdgui sjgbnsuih jhbisubh sjjskbhsug joij',
    blurhash: 'LBLENT%0ax_3~U4no#M{00xu%2IU',
  },
  {
    id: 8,
    img: '/assets/sale-10.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Reiciendis ducimus pariatur, natus soluta dolore maxime impedit rem quaerat! Ipsam, numquam. Minima lorem jsbnuibhjs n subjsoibgj sjgbnsdgui sjgbnsuih jhbisubh sjjskbhsug joij',
    blurhash: 'L4I3T[Or{a}nve%KyD,-[9]zAJ18',
  },
]

export const data = [
  {
    id: 1,
    img: '/assets/sale-1.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum dolor ',
    amount: 20,
    images: ['/assets/sale-6.jpg', '/assets/sale-2.jpg'],
    blurhash: 'L6BDyi?F009a00H??wtSlVp0m+w^',
  },
  {
    id: 2,
    img: '/assets/sale-2.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum dolor ',
    amount: 20,
    images: ['/assets/sale-3.jpg', '/assets/sale-2.jpg'],
    blurhash: 'LZKw?}?a.7V@~pIUV[WVxutQRQay',
  },
  {
    id: 3,
    img: '/assets/sale-3.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum ',
    amount: 20,
    images: ['/assets/sale-2.jpg', '/assets/sale-5.jpg'],
    blurhash: 'L8GSGoIUIB00Ot00WY~V9FX8-p?a',
  },
  {
    id: 4,
    img: '/assets/sale-4.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum ',
    amount: 20,
    images: ['/assets/sale-1.jpg', '/assets/sale-4.jpg'],
    blurhash: 'LFBNTi9EJCIUu6xuD$xvM_tSVWjE',
  },
  {
    id: 5,
    img: '/assets/sale-9.jpg',
    title: 'Solar Installation',
    desc: 'Lorem ipsum ',
    amount: 20,
    images: ['/assets/sale-2.jpg', '/assets/sale-3.jpg'],
    blurhash: 'L6O|U,00XSoz00aLIT?v_NkERORP',
  },
  {
    id: 6,
    img: '/assets/sale-6.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum dolor ',
    amount: 20,
    images: ['/assets/sale-1.jpg', '/assets/sale-2.jpg'],
    blurhash: 'LFBNTi9EJCIUu6xuD$xvM_tSVWjE',
  },
  {
    id: 7,
    img: '/assets/sale-7.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum ',
    amount: 20,
    images: ['/assets/sale-3.jpg', '/assets/sale-2.jpg'],
    blurhash: 'LFBNTi9EJCIUu6xuD$xvM_tSVWjE',
  },
  {
    id: 8,
    img: '/assets/sale-10.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum dolor ',
    amount: 20,
    images: ['/assets/sale-2.jpg', '/assets/sale-3.jpg'],
    blurhash: 'LFBNTi9EJCIUu6xuD$xvM_tSVWjE',
  },
  {
    id: 9,
    img: '/assets/sale-10.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum dolor ',
    amount: 20,
    images: ['/assets/sale-2.jpg', '/assets/sale-3.jpg'],
    blurhash: 'LFBNTi9EJCIUu6xuD$xvM_tSVWjE',
  },
  {
    id: 10,
    img: '/assets/sale-10.jpg',
    title: 'Mens T-shirt',
    desc: 'Lorem ipsum dolor ',
    amount: 20,
    images: ['/assets/sale-2.jpg', '/assets/sale-3.jpg'],
    blurhash: 'LFBNTi9EJCIUu6xuD$xvM_tSVWjE',
  },
]

export const singleProduct = {
  id: 1,
  img: '/assets/sale-1.jpg',
  title: 'Mens T-shirt',
  desc: 'Lorem ipsum dolor ',
  amount: 20,
  images: [
    '/assets/sale-6.jpg',
    '/assets/sale-2.jpg',
    '/assets/sale-8.jpg',
    '/assets/sale-3.jpg',
  ],
  blurhash: 'LFBNTi9EJCIUu6xuD$xvM_tSVWjE',
}
